name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3

       # v3.0.0
        # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 
  
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
    - name: Log into registry ghcr.io
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
          logout: false
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set environment variables
      run: |
        echo "LOWERCASE_REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          
 # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
      with:
          file: ./Lizzy/OneDrive/Documenten/Semester 3.2/Backend-Flixnet/FlixnetBackend/FlixnetBackend
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.LOWERCASE_REPO_NAME }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
